{% set name = "pypeec" %}
{% set version = "5.3.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypeec-{{ version }}.tar.gz
  sha256: 0a47e026d0e4a6b56d3e0f618a6c77e52dbd9aa8a5a3dfa4aa5a25f60e44d8dc

build:
  entry_points:
    - pypeec = pypeec:run_script
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68.2
    - wheel >=0.41
    - setuptools-scm >=7.1
    - pip >=24.2
  run:
    - python >={{ python_min }}
    - scilogger >=1.2
    - scisave >=1.4
    - jsonschema >=4.23
    - numpy >=1.24
    - scipy >=1.12
    - joblib >=1.3
    - vtk >=9.2
    - pyvista >=0.40
    - shapely >=2.0
    - rasterio >=1.3
    - pillow >=10.0
    - pyqt >=5.15
    - pyvistaqt >=0.11
    - matplotlib-base >=3.7
  
test:
  imports:
    - pypeec
    - pypeec.main
    - pypeec.script
    - pypeec.run.mesher
    - pypeec.run.solver
    - pypeec.run.viewer
    - pypeec.run.plotter
  commands:
    - pypeec --version
    - pypeec --help
  requires:
    - python {{ python_min }}
    - pip >=24.2

about:
  summary: PyPEEC - 3D Quasi-Magnetostatic Solver
  description: |
    PyPEEC is a 3D quasi-magnetostatic PEEC solver developed at Dartmouth
    College within the Power Management Integration Center (PMIC). PyPEEC 
    is a fast solver (FFT and GPU accelerated) that can simulate a large 
    variety of magnetic components (inductors, transformers, chokes, IPT 
    coils, busbars, etc.). The tool contains a mesher (STL, PNG, and GERBER 
    formats), a solver (static and frequency domain), and advanced plotting 
    capabilities. The code is written in Python and is fully open source!
  license: MPL-2.0
  license_file: LICENSE.txt
  doc_url: https://pypeec.otvam.ch
  dev_url: https://github.com/otvam/pypeec
  home: https://github.com/otvam/pypeec

extra:
  recipe-maintainers:
    - otvam
