{% set name = "pypeec" %}
{% set version = "5.7.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypeec-{{ version }}.tar.gz
  sha256: f5f669025629659b12ad449f0b2c03b5c0884183865b5030d498d0c0efa13a4f

build:
  entry_points:
    - pypeec = pypeec:run_script
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=78.1
    - setuptools-scm >=8.2
    - wheel >=0.45
    - pip >=25.0
  run:
    - python >={{ python_min }}
    - scilogger >=1.2.4
    - scisave >=1.6.0
    - jsonschema >=4.23.0
    - numpy >=1.24.0
    - scipy >=1.12.0
    - joblib >=1.3.0
    - vtk >=9.2.0
    - pyvista >=0.40.0
    - shapely >=2.0.0
    - rasterio >=1.3.0
    - pillow >=10.0.0
    - matplotlib-base >=3.7.0
    - qtpy >=2.4.0
    - pyside6 >=6.7.0
    - pyvistaqt >=0.11.0

test:
  imports:
    - pypeec
    - pypeec.main
    - pypeec.script
    - pypeec.run.mesher
    - pypeec.run.solver
    - pypeec.run.viewer
    - pypeec.run.plotter
  commands:
    - pypeec --version
    - pypeec --help
  requires:
    - python {{ python_min }}
    - pip >=24.3

about:
  summary: PyPEEC - 3D Quasi-Magnetostatic Solver
  description: |
    PyPEEC is a 3D quasi-magnetostatic PEEC solver developed at Dartmouth
    College within the Power Management Integration Center (PMIC). PyPEEC 
    is a fast solver (FFT and GPU accelerated) that can simulate a large 
    variety of magnetic components (inductors, transformers, chokes, IPT 
    coils, busbars, etc.). The tool contains a mesher (STL, PNG, and GERBER 
    formats), a solver (static and frequency domain), and advanced plotting 
    capabilities. The code is written in Python and is fully open source!
  license: MPL-2.0
  license_file: LICENSE.txt
  doc_url: https://pypeec.otvam.ch
  dev_url: https://github.com/otvam/pypeec
  home: https://github.com/otvam/pypeec

extra:
  recipe-maintainers:
    - otvam
