{% set name = "pypeec" %}
{% set version = "4.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypeec-{{ version }}.tar.gz
  sha256: 70c7a97282d740b30debe8927aa06ca24047172e565b0f58e928dd974f97dc01

build:
  entry_points:
    - pypeec = pypeec.script:run_script
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >68.2
    - wheel >0.41
    - setuptools-scm >7.1
    - pip
  run:
    - python >=3.9
    - pyyaml >=6.0
    - joblib >=1.3
    - numpy >=1.24
    - scipy >=1.9
    - matplotlib >=3.7
    - shapely >=2.0
    - rasterio >=1.3
    - pillow >=10.0
    - pyvista >=0.40
    - pyvistaqt >=0.11
    - pyqt >=5.15
    - vtk >=9.2

test:
  imports:
    - pypeec
    - pypeec.io
    - pypeec.log
    - pypeec.main
    - pypeec.script
    - pypeec.run.mesher
    - pypeec.run.solver
    - pypeec.run.viewer
    - pypeec.run.plotter
  commands:
    - pypeec --version
    - pypeec --help
  requires:
    - pip

about:
  summary: PyPEEC - 3D PEEC Solver
  description: |
    PyPEEC is a 3D quasi-magnetostatic PEEC solver developed at Dartmouth
    College within the Power Management Integration Center (PMIC). PyPEEC 
    is a fast solver (FFT and GPU accelerated) that can simulate a large 
    variety of magnetic components (inductors, transformers, chokes, IPT 
    coils, busbars, etc.). The tool contains a mesher (STL, PNG, and GERBER 
    formats), a solver (static and frequency domain), and advanced plotting 
    capabilities. The code is written in Python and is fully open source!
  license: MPL-2.0
  license_file: LICENSE.txt
  doc_url: https://pypeec.otvam.ch
  dev_url: https://github.com/otvam/pypeec
  home: https://github.com/otvam/pypeec

extra:
  recipe-maintainers:
    - otvam
